shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/**/*
  - stories/**/*
  - internals/**/*

ignoredBuiltDependencies:
  - '@aa900031/eslint-config'

onlyBuiltDependencies:
  - esbuild
  - vue-demi
