shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici@6.22.0

packages:
  - packages/**/*
  - stories/**/*
  - internals/**/*

ignoredBuiltDependencies:
  - '@aa900031/eslint-config'

onlyBuiltDependencies:
  - esbuild
  - vue-demi
