shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/**/*
  - stories/**/*
  - internals/**/*

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - esbuild
  - vue-demi
